pixiu-io/kubez-ansible

- tests/toolbox.yaml
Change-Id: Ib533827ac4c37dcd62d29de384ff28c684eccd03
> Add toolbox pod for debug needed

- ansible/group_vars/all.yml
- ansible/library/kube_toolbox.py
- etc/kubez/globals.yml
- tests/toolbox.yaml
Change-Id: I3ca650061750f4df6cb16c9358acae509022a3c2
> Add external slb for  kube-apiserver

- README.md
- tools/all_in_one.sh
- tools/setup_env.sh
Change-Id: Iee2a999480f5139fb71102a9085c28ecc13984a8
> Install ansible by yum/apt-get

- ansible/group_vars/all.yml
- ansible/roles/helm-apply/defaults/main.yml
- ansible/roles/helm-apply/tasks/main.yaml
- ansible/roles/kubernetes/tasks/addons.yml
- etc/kubez/globals.yml
Change-Id: Ic301529ed0755a3a3195546f8696a6e3cb4ec15f
> Complete helm-apply role 

- ansible/roles/kubernetes/templates/metrics-server.yml.j2
Reverts caoyingjunz/kubez-ansible#69
> Update extra-cpu for metric installed

- ansible/library/helm_toolbox.py
- ansible/roles/helm-apply/defaults/main.yml
- ansible/roles/helm-apply/tasks/main.yaml
- ansible/roles/kubernetes/tasks/addons.yml
Change-Id: Ib4907889fae54dcf1d083ffe66dcaeefe62de2bf
> Add chart_extra_flags supported for helm_toolbox module

- ansible/group_vars/all.yml
- etc/kubez/globals.yml
Change-Id: Id373d3b6e6d0e285438ed1c4dd2564493d8cbd77
> Add efk installed by helm

- README.md
- ansible/group_vars/all.yml
- etc/kubez/globals.yml
Change-Id: Ifa9b5916aa713566094fb3470aaca9e52e8b356c
> Add fluentd install supported by helm_toolbox

- ansible/group_vars/all.yml
- ansible/roles/kubernetes/files/setup_helm.sh
- ansible/roles/kubernetes/tasks/addons.yml
- ansible/roles/kubernetes/templates/helm.yml.j2
- etc/kubez/globals.yml
Change-Id: Ie9341719774ca33404d48a11aca1c64bf230978f
> Refactor the helm installed step

- README.md
更新README.md文档，为基础组件Helm3补充了URL
> Update README.md, add URL for the base component helm3 documentation

- ansible/group_vars/all.yml
- etc/kubez/globals.yml
delete redis config from ansible/group_vars/all.yml, it will not installed by helm
> 从all.yaml删除不需要的redis定义#134

- ansible/group_vars/all.yml
- ansible/library/kube_toolbox.py
- ansible/roles/kubernetes/tasks/config.yml
Change-Id: I751d8d60fd1be26e936b949905bb514b968c376b
> To fix master rename label and taint keys to control-plane

- docs/paas/kafka.md
- docs/paas/mongodb.md
- docs/paas/postgres.md
- docs/paas/rabbitmq.md
- docs/paas/redis.md
Postgres，Rabbitmq，Mongodb，Kafka,Redis
> Optimize middleware parameters

- ansible/group_vars/all.yml
- etc/kubez/globals.yml
1、部署promtail
2、部署loki
3、通过grafana添加loki数据源查看日志
> 添加组件 promtail 和 loki 的支持

- docs/apply/prometheus.md
> Update prometheus.md pr

- README.md
> Fix MD File

- docs/apply/ingress.md
- docs/apply/metrics.md
> fix misspelling

- ansible/post-deploy.yml
> 支持 kubernetes 自动补全命令

- docs/apply/jenkins.md
- tools/setup_env.sh
reduce magic value and extract branch as parameter. more conducive to maintenance and expansion.
> Drop the clone for getting kubez-ansible

- README.md
- ansible/group_vars/all.yml
- docs/apply/cilium.md
- etc/kubez/globals.yml
Change-Id: Ib4a6b986be5ed3b0a9d0f6fe78f014098483aca6
> Add Cilium&Hubble supported

- ansible/group_vars/all.yml
- etc/kubez/globals.yml
Change-Id: I4cfe2f68f7879fd8ed1012730bc01746f3a79a90
> Add custom helm chart repo supported (#400)

- ansible/library/kube_toolbox.py
Change-Id: If924128a39dd3d9c82ebdf3805fdaf81f08d9d87
> 修复添加节点 socket 为空的问题

- ansible/roles/baremetal/templates/config.toml.j2
> 修改systemd_cgroup值

- ansible/roles/baremetal/tasks/install.yml
- ansible/roles/baremetal/tasks/pre-install.yml
Change-Id: I5b2fefa466161922878cfe58d11f3e31be3a1e93
> Update apt cache for default source

- ansible/roles/baremetal/tasks/install.yml
- ansible/roles/baremetal/tasks/pre-install.yml
Change-Id: I5b2fefa466161922878cfe58d11f3e31be3a1e93
> Update apt cache for default source (#468)

- ansible/roles/kubernetes/templates/kube-flannel.yml.j2
Change-Id: I401efe2e120215dbfe97efd5b82d7d71f580a9dd
> Bump flannel version to v0.25.4

- ansible/roles/kubernetes/templates/kube-flannel.yml.j2
Change-Id: I82cb39800cbf67bb85821899adf419cb86322a52
> Bump flannel version to v0.25.4 (#470)

- ansible/group_vars/all.yml
- ansible/library/gpg_key.py
- ansible/roles/baremetal/tasks/install.yml
- ansible/roles/baremetal/templates/kubernetes.repo.j2
- ansible/roles/baremetal/templates/sources.list.debian.j2
- ansible/roles/baremetal/templates/sources.list.j2
Change-Id: I4b7c7d9f9a78a83635601243286f58e4b7d1aa0f
> Support  installation of higher versions of Kubernetes (#492)

- docs/install/prerequisites.md
⚠️Fix tiger branch script download issue
> Fix tiger branch script download issue
